name       : mosh
version    : 1.2.5
release    : 1
source     :
    - https://github.com/mobile-shell/mosh/releases/download/mosh-1.2.5/mosh-1.2.5.tar.gz : 1af809e5d747c333a852fbf7acdbf4d354dc4bbc2839e3afe5cf798190074be3
license    : GPL-3.0
summary    : Mosh is a remote terminal application that supports intermittent connectivity.
description: |
    Mosh is a remote terminal application that supports intermittent connectivity
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
