name       : mosh
version    : 1.2.6
release    : 4
source     :
    - https://github.com/mobile-shell/mosh/releases/download/mosh-1.2.6/mosh-1.2.6.tar.gz : 7e82b7fbfcc698c70f5843bb960dadb8e7bd7ac1d4d2151c9d979372ea850e85
license    : GPL-3.0
summary    : Mosh is a remote terminal application that supports intermittent connectivity.
component  : network.clients
description: |
    Mosh is a remote terminal application that supports intermittent connectivity
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
