name       : mosh
version    : 1.3.0
release    : 5
source     :
    - https://github.com/mobile-shell/mosh/releases/download/mosh-1.3.0/mosh-1.3.0.tar.gz : 320e12f461e55d71566597976bd9440ba6c5265fa68fbf614c6f1c8401f93376
license    : GPL-3.0
summary    : Mosh is a remote terminal application that supports intermittent connectivity.
component  : network.clients
description: |
    Mosh is a remote terminal application that supports intermittent connectivity
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
