name       : mosh
version    : 1.3.2
release    : 16
source     :
    - https://github.com/mobile-shell/mosh/archive/mosh-1.3.2.tar.gz : e7f69404816f1ca5b44762d010e406a56d18e133d31efd0783970de8d6c80ed4
license    : GPL-3.0-or-later
summary    : Mosh is a remote terminal application that supports intermittent connectivity.
component  : network.clients
description: |
    Mosh is a remote terminal application that supports intermittent connectivity
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(protobuf)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
